# Generated by Django 4.2.5 on 2023-09-30 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "product gallery",
                "verbose_name_plural": "product gallery",
            },
        ),
    ]
